version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: wechat-archive
      MYSQL_ROOT_PASSWORD: wechat-archive
    volumes: 
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
